services:
  traffilearn-webapi:
    image: ${DOCKER_REGISTRY-}traffilearnwebapi
    container_name: traffilearn.api
    build:
      context: .
      dockerfile: TraffiLearn.WebAPI/Dockerfile
    ports:
      - "5000:5000"
    depends_on: 
      - traffilearn-database
      - traffilearn-blob-storage

  traffilearn-database:
    container_name: traffilearn.database
    image: postgres:latest
    environment:
      - POSTGRES_DB=traffilearn
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - traffilearn_postgresdb_data:/var/lib/postgresql/data

  traffilearn-blob-storage:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    container_name: traffilearn.azurite
    ports:
      - "10000:10000"
    command: "azurite-blob --blobHost 0.0.0.0 -l /data"
    volumes:
      - traffilearn_blob_data:/data
        
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    environment:
      - MH_STORAGE=maildir

  traffilearn-rabbitmq:
    image: rabbitmq:4.0.4-management
    container_name: traffilearn.rabbitmq
    hostname: traffilearn-queue
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
        - traffilearn_rabbitmq_data:/var/lib/rabbitmq
        - traffilearn_rabbitmq_logs:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASSWORD: guest

volumes:
  traffilearn_postgresdb_data:
  traffilearn_blob_data:
  traffilearn_rabbitmq_data:
  traffilearn_rabbitmq_logs:  